var data={
  "labels": [
    "03/10",
    "03/11",
    "03/12",
    "03/13",
    "03/14",
    "03/15",
    "03/16",
    "03/17",
    "03/18",
    "03/19",
    "03/20",
    "03/21",
    "03/22",
    "03/23",
    "03/24",
    "03/25",
    "03/26",
    "03/27",
    "03/28",
    "03/29"
  ],
  "sets": [
    {
      "label": "Illinois",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(25, 60%, 50%)",
      "backgroundColor": "hsl(25, 60%, 50%)",
      "data": [
        20,
        25,
        32,
        46,
        64,
        93,
        105,
        160,
        288,
        422,
        585,
        753,
        1046,
        1283,
        1535,
        1865,
        2538,
        3026,
        3491,
        4596
      ]
    },
    {
      "label": "Chicago",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(14, 60%, 50%)",
      "backgroundColor": "hsl(14, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        519,
        636,
        null,
        782,
        1161,
        1364,
        1610,
        2026
      ]
    },
    {
      "label": "Adams",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(308, 60%, 50%)",
      "backgroundColor": "hsl(308, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        2
      ]
    },
    {
      "label": "Bond",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(173, 60%, 50%)",
      "backgroundColor": "hsl(173, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        0,
        1
      ]
    },
    {
      "label": "Bureau",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(116, 60%, 50%)",
      "backgroundColor": "hsl(116, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        1,
        1,
        1
      ]
    },
    {
      "label": "Carroll",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(228, 60%, 50%)",
      "backgroundColor": "hsl(228, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        1,
        1
      ]
    },
    {
      "label": "Champaign",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(203, 60%, 50%)",
      "backgroundColor": "hsl(203, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        2,
        2,
        null,
        2,
        8,
        10,
        11,
        21
      ]
    },
    {
      "label": "Christian",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(335, 60%, 50%)",
      "backgroundColor": "hsl(335, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        6
      ]
    },
    {
      "label": "Clinton",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(309, 60%, 50%)",
      "backgroundColor": "hsl(309, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        3,
        null,
        3,
        null,
        3,
        3,
        null,
        3,
        5,
        5,
        5,
        6
      ]
    },
    {
      "label": "Cook",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(188, 60%, 50%)",
      "backgroundColor": "hsl(188, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        107,
        178,
        null,
        411,
        null,
        286,
        286,
        null,
        412,
        743,
        875,
        1003,
        1419
      ]
    },
    {
      "label": "Cumberland",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(41, 60%, 50%)",
      "backgroundColor": "hsl(41, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "DeKalb",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(239, 60%, 50%)",
      "backgroundColor": "hsl(239, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        1,
        1,
        null,
        1,
        3,
        4,
        4,
        8
      ]
    },
    {
      "label": "Douglas",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(228, 60%, 50%)",
      "backgroundColor": "hsl(228, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "DuPage",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(266, 60%, 50%)",
      "backgroundColor": "hsl(266, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        26,
        45,
        null,
        57,
        null,
        79,
        95,
        null,
        103,
        182,
        199,
        202,
        274
      ]
    },
    {
      "label": "Fayette",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(280, 60%, 50%)",
      "backgroundColor": "hsl(280, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        1,
        1
      ]
    },
    {
      "label": "Franklin",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(65, 60%, 50%)",
      "backgroundColor": "hsl(65, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        1,
        1,
        1,
        2
      ]
    },
    {
      "label": "Grundy",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(280, 60%, 50%)",
      "backgroundColor": "hsl(280, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        1,
        2,
        2,
        2,
        3
      ]
    },
    {
      "label": "Henry",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(295, 60%, 50%)",
      "backgroundColor": "hsl(295, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        1,
        2,
        2
      ]
    },
    {
      "label": "Iroquois",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(136, 60%, 50%)",
      "backgroundColor": "hsl(136, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        1,
        2,
        2
      ]
    },
    {
      "label": "Jackson",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(217, 60%, 50%)",
      "backgroundColor": "hsl(217, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        2,
        3
      ]
    },
    {
      "label": "Jo Daviess",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(55, 60%, 50%)",
      "backgroundColor": "hsl(55, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "Kane",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(83, 60%, 50%)",
      "backgroundColor": "hsl(83, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3,
        4,
        null,
        8,
        null,
        13,
        18,
        null,
        24,
        57,
        75,
        90,
        100
      ]
    },
    {
      "label": "Kankakee",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(234, 60%, 50%)",
      "backgroundColor": "hsl(234, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        2,
        3,
        null,
        4,
        15,
        17,
        27,
        33
      ]
    },
    {
      "label": "Kendall",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(325, 60%, 50%)",
      "backgroundColor": "hsl(325, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        2,
        null,
        2,
        null,
        4,
        4,
        null,
        4,
        7,
        8,
        11,
        15
      ]
    },
    {
      "label": "Knox",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(91, 60%, 50%)",
      "backgroundColor": "hsl(91, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        0,
        1
      ]
    },
    {
      "label": "Lake",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(79, 60%, 50%)",
      "backgroundColor": "hsl(79, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        7,
        18,
        null,
        53,
        null,
        69,
        96,
        null,
        111,
        185,
        230,
        241,
        300
      ]
    },
    {
      "label": "LaSalle",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(167, 60%, 50%)",
      "backgroundColor": "hsl(167, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        1,
        2,
        null,
        3,
        3,
        3,
        3,
        4
      ]
    },
    {
      "label": "Livingston",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(221, 60%, 50%)",
      "backgroundColor": "hsl(221, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        1,
        1,
        null,
        1,
        1,
        2,
        2,
        2
      ]
    },
    {
      "label": "McHenry",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(164, 60%, 50%)",
      "backgroundColor": "hsl(164, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        4,
        null,
        8,
        null,
        12,
        12,
        null,
        14,
        27,
        45,
        47,
        52
      ]
    },
    {
      "label": "McLean",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(66, 60%, 50%)",
      "backgroundColor": "hsl(66, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        4,
        null,
        6,
        7,
        null,
        7,
        7,
        10,
        10,
        14
      ]
    },
    {
      "label": "Macon",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(353, 60%, 50%)",
      "backgroundColor": "hsl(353, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        1,
        2
      ]
    },
    {
      "label": "Madison",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(334, 60%, 50%)",
      "backgroundColor": "hsl(334, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        1,
        null,
        1,
        null,
        2,
        2,
        null,
        2,
        6,
        8,
        10,
        12
      ]
    },
    {
      "label": "Marshall",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(349, 60%, 50%)",
      "backgroundColor": "hsl(349, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "Menard",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(76, 60%, 50%)",
      "backgroundColor": "hsl(76, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        0,
        1
      ]
    },
    {
      "label": "Monroe",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(127, 60%, 50%)",
      "backgroundColor": "hsl(127, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        1,
        null,
        1,
        3,
        3,
        3,
        3
      ]
    },
    {
      "label": "Montgomery",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(197, 60%, 50%)",
      "backgroundColor": "hsl(197, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        0,
        0,
        0,
        1
      ]
    },
    {
      "label": "Morgan",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(116, 60%, 50%)",
      "backgroundColor": "hsl(116, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        1,
        1,
        3,
        3
      ]
    },
    {
      "label": "Peoria",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(285, 60%, 50%)",
      "backgroundColor": "hsl(285, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        3,
        null,
        3,
        null,
        3,
        3,
        null,
        3,
        5,
        6,
        7,
        8
      ]
    },
    {
      "label": "Rock Island",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(286, 60%, 50%)",
      "backgroundColor": "hsl(286, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        1,
        1,
        null,
        1,
        4,
        4,
        4,
        5
      ]
    },
    {
      "label": "St. Clair",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(287, 60%, 50%)",
      "backgroundColor": "hsl(287, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        3,
        null,
        3,
        null,
        3,
        4,
        null,
        7,
        13,
        15,
        18,
        31
      ]
    },
    {
      "label": "Sangamon",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(349, 60%, 50%)",
      "backgroundColor": "hsl(349, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3,
        3,
        null,
        4,
        null,
        4,
        4,
        null,
        5,
        7,
        7,
        8,
        9
      ]
    },
    {
      "label": "Stephenson",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(126, 60%, 50%)",
      "backgroundColor": "hsl(126, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        1,
        1,
        null,
        1,
        2,
        2,
        2,
        3
      ]
    },
    {
      "label": "Tazewell",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(258, 60%, 50%)",
      "backgroundColor": "hsl(258, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        2,
        2,
        3,
        4
      ]
    },
    {
      "label": "Washington",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(66, 60%, 50%)",
      "backgroundColor": "hsl(66, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "Whiteside",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(157, 60%, 50%)",
      "backgroundColor": "hsl(157, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        1,
        1,
        null,
        1,
        1,
        2,
        2,
        3
      ]
    },
    {
      "label": "Will",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(9, 60%, 50%)",
      "backgroundColor": "hsl(9, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        3,
        null,
        10,
        null,
        21,
        24,
        null,
        28,
        67,
        104,
        127,
        182
      ]
    },
    {
      "label": "Williamson",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(197, 60%, 50%)",
      "backgroundColor": "hsl(197, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        1,
        null,
        0,
        1,
        null,
        1,
        1,
        1,
        1,
        1
      ]
    },
    {
      "label": "Winnebago",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(177, 60%, 50%)",
      "backgroundColor": "hsl(177, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        2,
        null,
        4,
        5,
        null,
        5,
        8,
        8,
        9,
        12
      ]
    },
    {
      "label": "Woodford",
      "lineTension": 0,
      "pointRadius": 5,
      "pointHoverRadius": 7,
      "pointHitRadius": 30,
      "fill": false,
      "spanGaps": true,
      "borderColor": "hsl(171, 60%, 50%)",
      "backgroundColor": "hsl(171, 60%, 50%)",
      "data": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        2,
        null,
        2,
        2,
        null,
        3,
        3,
        3,
        3,
        3
      ]
    }
  ],
  "updated": "March 29, 2020"
};